#pragma once

// Internal DLL export symbol table
#define SYM_INIT            "OpenDevice"
#define SYM_RELEASE         "Close"
#define SYM_SEND_ABS        "MoveTo"
#define SYM_SEND_DELTA      "MoveR"
#define SYM_SEND_DELTA_STEP "MoveRD"
#define SYM_PRESS_CODE      "KeyDownName"
#define SYM_RELEASE_CODE    "KeyUpName"
#define SYM_TAP_CODE        "KeyPressName"
#define SYM_QUERY_STATE     "DllGetKeyState"
#define SYM_BTN_PRESS       "MouseButtonDown"
#define SYM_BTN_RELEASE     "MouseButtonUp"
#define SYM_BTN_TAP         "MouseButtonClick"
#define SYM_RESTART         "Reboot"
#define SYM_CLEAR_ALL       "KeyAllup"
#define SYM_CIPHER          "SetEncrypt"
#define SYM_UNIT_ID         "GetChipID"
#define SYM_BUILD_NUM       "GetVersion"
#define SYM_UNIT_TYPE       "GetModel"
#define SYM_SYNC_MODE       "SetWaitRespon"
#define SYM_CHECK_ACTIVE    "IsOpen"
#define SYM_INIT_BY_ID      "OpenDeviceByID"
#define SYM_BATCH_INTERVAL  "CombineMoveR"
#define SYM_LOCK_INPUT      "Lock_KeyBoard"
#define SYM_RELEASE_BY_ID   "KeyUpVirtualCode"
#define SYM_LOCK_CURSOR     "Lock_Mouse"
